// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConvertToMP4(arg1:string):Promise<main.ConversionResult>;

export function InstallFFmpeg():Promise<void>;

export function IsFFmpegInstalled():Promise<boolean>;

export function OpenOutputFolder(arg1:string):Promise<void>;

export function SelectFiles():Promise<Array<string>>;
