// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertToMP4(arg1) {
  return window['go']['main']['App']['ConvertToMP4'](arg1);
}

export function InstallFFmpeg() {
  return window['go']['main']['App']['InstallFFmpeg']();
}

export function IsFFmpegInstalled() {
  return window['go']['main']['App']['IsFFmpegInstalled']();
}

export function OpenOutputFolder(arg1) {
  return window['go']['main']['App']['OpenOutputFolder'](arg1);
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}
